options:
  merge-default-rules: true
rules:
  class-name-format:
    - 2
    - allow-leading-underscore: false
      convention: hyphenatedbem
  property-sort-order:
    # Disabled due to https://github.com/sasstools/sass-lint/issues/1189
    - 0
    # - 2
    # - order: concentric
