language: node_js
node_js: --lts # LTS
cache:
  directories:
    - $HOME/.npm
env:
  global:
    - AWS_S3_BUCKET=amercier-tools
    - AWS_S3_REGION=eu-west-3
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - npm run lint
script:
  - npm test -- --coverage
after_success:
  - codecov
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
before_deploy:
  - npm run build
  - pip install --user awscli
deploy:
  provider: script
  skip_cleanup: true
  on:
    branch: master
  # Note: AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY must be set in Travis project settings
  script: ~/.local/bin/aws s3 sync build s3://${AWS_S3_BUCKET} --region=${AWS_S3_REGION} --delete
after_deploy:
  - curl --fail --silent --show-error http://${AWS_S3_BUCKET}.s3-website.${AWS_S3_REGION}.amazonaws.com/
  # Invalidates only index.html as other files are versioned
  # Note: CLOUDFRONT_DISTRIBUTION_ID must be set in Travis project settings
  - ~/.local/bin/aws configure set preview.cloudfront true
  - ~/.local/bin/aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths /index.html
