language: node_js
node_js: node # Current
cache: yarn
before_deploy:
  - yarn build
  - pip install --user awscli
deploy:
  provider: script
  # Note: AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY must be set in Travis project settings
  script: ~/.local/bin/aws s3 sync build s3://amercier-tools --region=eu-west-3 --delete
  on:
    branch: master
  skip_cleanup: true
